CREATE ROLE IF NOT EXISTS {{env}}_ROLE;
CREATE ROLE IF NOT EXISTS PROD_ROLE;


GRANT ROLE {{env}}_ROLE TO USER tdiallo;
GRANT ROLE PROD_ROLE TO USER tdiallo;


CREATE WAREHOUSE IF NOT EXISTS {{env}}_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS PROD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE, OPERATE ON WAREHOUSE {{env}}_WH TO ROLE {{env}}_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE PROD_WH TO ROLE PROD_ROLE;


CREATE DATABASE IF NOT EXISTS DB_POLLUTION_{{env}};
CREATE DATABASE IF NOT EXISTS DB_POLLUTION;


CREATE SCHEMA IF NOT EXISTS DB_POLLUTION_{{env}}.LANDING;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION_{{env}}.RAW;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION_{{env}}.STAGING;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION_{{env}}.MARTS;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION_{{env}}.MONITORING;

CREATE SCHEMA IF NOT EXISTS DB_POLLUTION.LANDING;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION.RAW;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION.STAGING;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION.MARTS;
CREATE SCHEMA IF NOT EXISTS DB_POLLUTION.MONITORING;


GRANT EXECUTE TASK ON ACCOUNT TO ROLE {{env}}_ROLE;
GRANT USAGE ON DATABASE DB_POLLUTION_{{env}} TO ROLE {{env}}_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DB_POLLUTION_{{env}} TO ROLE {{env}}_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DB_POLLUTION_{{env}} TO ROLE {{env}}_ROLE;

GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE VIEW, CREATE STAGE, CREATE TASK, CREATE STREAMLIT, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON ALL SCHEMAS IN DATABASE DB_POLLUTION_{{env}} TO ROLE {{env}}_ROLE;

GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE VIEW, CREATE STAGE, CREATE TASK, CREATE STREAMLIT, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON FUTURE SCHEMAS IN DATABASE DB_POLLUTION_{{env}} TO ROLE {{env}}_ROLE;


GRANT EXECUTE TASK ON ACCOUNT TO ROLE PROD_ROLE;
GRANT USAGE ON DATABASE DB_POLLUTION TO ROLE PROD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DB_POLLUTION TO ROLE PROD_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DB_POLLUTION TO ROLE PROD_ROLE;

GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE VIEW, CREATE STAGE, CREATE TASK, CREATE STREAMLIT, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON ALL SCHEMAS IN DATABASE DB_POLLUTION TO ROLE PROD_ROLE;

GRANT CREATE TABLE, CREATE DYNAMIC TABLE, CREATE VIEW, CREATE STAGE, CREATE TASK, CREATE STREAMLIT, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
  ON FUTURE SCHEMAS IN DATABASE DB_POLLUTION TO ROLE PROD_ROLE;
